[build]
  command = "npm run production"
  publish = "dist"

[[redirects]]
  from = "/pages/about"
  to = "/about"

[[redirects]]
  from = "/pages/interests"
  to = "/interests"

[[redirects]]
  from = "/pages/research"
  to = "/research"

[[redirects]]
  from = "/pages/resources"
  to = "/resources"

[[redirects]]
  from = "/pages/projects"
  to = "/projects"

# Proxying Plausible through Netlify
# @see https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
  from = "/masked-source/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/masked-source/api/event"
  to = "https://plausible.io/api/event"
  status = 200

  